[project]
name = "ligand-grokking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "polars[deltalake]>=1.33.1",
    "rdkit>=2025.3.6",
]

[dependency-groups]
dev = [
    "jedi-language-server>=0.45.1",
    "ruff>=0.13.0",
]
